runtime: python39
entrypoint: streamlit run app.py



# runtime: python
# env: flex

# runtime_config:
#   python_version: 38

# entrypoint: streamlit run app.py --server.port $PORT

# automatic_scaling:
#   max_num_instances: 1
