runtime: python39
env: flex

# Add this line to allow traffic from any source
inbound_services:
  - '*'
  
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 20 

entrypoint: streamlit run app.py

automatic_scaling:
  max_num_instances: 1
