runtime: python39
entrypoint: streamlit run app.py

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 20 

# runtime: python
# env: flex

# runtime_config:
#   python_version: 38

# entrypoint: streamlit run app.py --server.port $PORT

# automatic_scaling:
#   max_num_instances: 1
